pipeline {
    agent any
    
    tools {
        nodejs "nodejs"
        maven "maven"
    }

    options{
        disableConcurrentBuilds()
    }

    environment {
        buildScript = 'build --configuration=docker'

        angularDir = 'angular'

        srcDir = 'src'

        sonarTool = 'SonarScanner'

        sonarEnv = "SonarQube"

        dockerTool = 'docker-global'
    }

    stages {
        stage ('Install Application') {
            steps {
                dir(angularDir) {
                    sh """npm install"""
                }
            }
        }

        stage ('SonarQube Code Analysis') {
            steps {
                script {
                    def scannerHome = tool sonarTool
                    def props = readJSON file: 'package.json'
                    withSonarQubeEnv(sonarEnv) {
                        sh """mvn clean package sonar:sonar"""
                    }
                }
            }
        }

        stage ('Build Application') {
            steps {
                dir(angularDir) {
                    sh """npm run build"""
                }
            }
        }

        stage ('Create The Docker Image') {
            steps {
                dir(angularDir) {
                    sh """docker build -t jump-the-queue/angular ."""
                }
            }
        }
    }
}
