pipeline {
    agent any
    
    tools {
        nodejs "nodejs"
    }

    options{
        disableConcurrentBuilds()
    }

    environment {
        buildScript = 'build --configuration=docker'

        angularDir = 'angular'

        srcDir = 'angular/src'

        sonarTool = 'SonarScanner'

        sonarEnv = "SonarQube"

        dockerTool = 'docker'
    }

    stages {
        stage ('Install Application') {
            steps {
                dir(angularDir) {
                    sh """npm install"""
                }
            }
        }

        stage ('SonarQube Code Analysis') {
            steps {
                script {
                    def scannerHome = tool sonarTool
                    withSonarQubeEnv(sonarEnv) {
                        sh """${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=angular \
                            -Dsonar.sources=${srcDir}
                        """
                    }
                }
            }
        }

        stage ('Build Application') {
            steps {
                dir(angularDir) {
                    sh """npm run build"""
                }
            }
        }

        stage ('Create The Docker Image') {
            steps {
                script {
                    dir(angularDir) {
                        tool dockerTool
                        docker.withTool(dockerTool) {
                            def image = docker.build("jump-the-queue/angular")
                        }
                    }
                }
            }
        }
    }
}
