pipeline {
    agent any

    tools {
        maven "maven"
        jdk "OpenJDK11"
    }

    environment {
        javarDir = 'java/jtqj'

        sonarTool = 'SonarScanner'

        sonarEnv = "SonarQube"

        nexusUrl = 'http://localhost:8090/repository/jump-the-queue/'

        dockerRegistryCredentials = 'nexus'

        dockerTool = 'docker'
    }

    stages {
        stage ('Install Application') {
            steps {
                dir(javarDir) {
                    sh """mvn clean install"""
                }
            }
        }

        stage ('Unit Tests') {
            steps {
                dir(javarDir) {
                    sh """mvn clean test"""
                }
            }
        }

        stage ('SonarQube Code Analysis') {
            steps {
                script {
                    def scannerHome = tool sonarTool
                    withSonarQubeEnv(sonarEnv) {
                        sh """${sonarHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=java \
                            -Dsonar.sources=${javaDir}
                        """
                    }
                }
            }
        }

        stage ('Build Application') {
            steps {
                dir(javaDir) {
                    sh """mvn clean package"""
                }
            }
        }

        stage ('Create The Docker Image & Upload To Nexus') {
            steps {
                script {
                    dir(javaDir){
                        tool dockerTool
                        docker.withTool(dockerTool) {
                            docker.withRegistry(nexusUrl, dockerRegistryCredentials) {
                                def image = docker.buil("java")
                                image.push("latest")
                            }
                        }
                    }
                }
            }
        }
    }
}